name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push Docker Image"
    runs-on: self-hosted

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up QEMU for cross-platform builds"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build and Push Docker Image for x64"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/github-actions-runner:1.0.0-amd64

      - name: "Build and Push Docker Image for arm64"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/github-actions-runner:1.0.0-arm64

      - name: "Logout from Docker Hub"
        run: docker logout